# Generated by Django 4.0.3 on 2022-03-11 09:51

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('name', models.CharField(help_text='format: required, max-200', max_length=200, verbose_name='recipe name')),
                ('description', tinymce.models.HTMLField(help_text='format: required', verbose_name='recipe description')),
                ('ingredients', tinymce.models.HTMLField(help_text='format: required', verbose_name='recipe description')),
                ('slug', models.SlugField(blank=True, help_text='format: required, letters, numbers, underscore, or hyphens', max_length=150, null=True, unique=True, verbose_name='recipe safe URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='format: Y-m-d H:M:S', verbose_name='date recipe created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='format: Y-m-d H:M:S', verbose_name='date recipe last updated')),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('title', models.CharField(help_text='format: required, max-200', max_length=200, verbose_name='blog title')),
                ('description', models.TextField(help_text='format: required', verbose_name='blog description')),
                ('slug', models.SlugField(blank=True, help_text='format: required, letters, numbers, underscore, or hyphens', max_length=150, null=True, unique=True, verbose_name='blog safe URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='format: Y-m-d H:M:S', verbose_name='date blog created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='format: Y-m-d H:M:S', verbose_name='date blog last updated')),
                ('is_active', models.BooleanField(default=False, verbose_name='is the blog active?')),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.recipe')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
